org: hong95
app: sls-flask-screenshot-gallery-app
service: sls-flask-screenshot-gallery-app

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
